.TH CREDITS-CLI "1" "November 2016" "credits-cli 1.0"
.SH NAME
credits-cli \- a remote procedure call client for Credits. 
.SH SYNOPSIS
credits-cli [options] <command> [params] \- Send command to Credits. 
.TP
credits-cli [options] help \- Asks Credits for a list of supported commands.
.SH DESCRIPTION
This manual page documents the credits-cli program. credits-cli is an RPC client used to send commands to Credits.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
